name: My First Workflow
on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Hello World
        run: echo 'Hello World'
      - name: My Second Step
        run : echo 'This is another message'
